/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h> // for NULL
#include <assert.h>
#include <string.h>
#include "gain_control.h"
#include "noise_suppression_x.h"
#include "noise_suppression.h"
#include "Platform.h"
#ifndef _Included_com_wzc_tools_WebrtcUtils
#define _Included_com_wzc_tools_WebrtcUtils

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_create
        (JNIEnv *env, jclass jclazz){
    void *agcInstance = NULL;
    WebRtcAgc_Create(&agcInstance);
    return ((int) agcInstance);

}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    init
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_init
        (JNIEnv *env, jclass jclazz, jint agcInstance, jint minLevel, jint maxLevel, jint agcMode, jint fs){

    void *agcInst = (void *) agcInstance;
    if (agcInst == NULL)
        return -5;

    return WebRtcAgc_Init(agcInst,minLevel,maxLevel,kAgcModeFixedDigital,fs);
}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    free
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_free
(JNIEnv *env, jclass jclazz, jint agcInstance){
    void *agcInst = (void *) agcInstance;
    if (agcInst == NULL)
        return -2;
    return WebRtcAgc_Free(agcInst);

}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    process
 * Signature: (I[SII[SIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_process
        (JNIEnv *env, jclass jclazz, jint agcInstance, const jshortArray inNear, jint num_bands, jint samples, jshortArray out, jint inMicLevel, jint outMicLevel, jint echo, jint saturationWarning){

        int16_t *arrNear = NULL;
        int16_t *arrOut = NULL;
        int32_t *outMicLevel1 = NULL;
        uint8_t *test = NULL;
        const int16_t* inNear_H = NULL;
        int16_t* out_H = NULL;


        void *agcInst = (void *) agcInstance;
        if(agcInst == NULL)
        return -1;

        int ret = -1;


        arrNear = (*env)->GetShortArrayElements(env,inNear, NULL);
        arrOut = (*env)->GetShortArrayElements(env,out, NULL);

        ret = WebRtcAgc_Process(agcInst,arrNear,inNear_H,samples,arrOut,out_H,inMicLevel,&outMicLevel1,echo,&test);

        //release and send the changes back to java side.
        (*env)->ReleaseShortArrayElements(env,inNear, arrNear, 0);
        (*env)->ReleaseShortArrayElements(env,out, arrOut, 0);

         return ret;
}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    setConfig
 * Signature: (ILcom/wzc/agc/AgcUtils/WebRtcAgcConfig;)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_setConfig
        (JNIEnv *env, jclass jclazz, jint agcInstance, jobject agcConfig){

        void * agcInst = (void *) agcInstance;
        if (agcInst == NULL)
        return -1;

        jclass JavaWebRtcAgcConfig = (*env)->GetObjectClass(env,agcConfig);
        assert(JavaWebRtcAgcConfig != NULL);
        jfieldID targetLevelDbfsID = (*env)->GetFieldID(env,JavaWebRtcAgcConfig, "targetLevelDbfs",
                                       "I");
        jfieldID compressionGaindBID = (*env)->GetFieldID(env,JavaWebRtcAgcConfig, "compressionGaindB",
                                      "I");
        jfieldID limiterEnableID = (*env)->GetFieldID(env,JavaWebRtcAgcConfig, "limiterEnable",
                                      "I");
        if (targetLevelDbfsID == NULL || compressionGaindBID == NULL || limiterEnableID == NULL)
        return -1;

        int targetLevelDbfsMode = (*env)->GetIntField(env,agcConfig, targetLevelDbfsID);
        int compressionGaindBMode = (*env)->GetIntField(env,agcConfig, compressionGaindBID);
        int limiterEnableMode = (*env)->GetIntField(env,agcConfig, limiterEnableID);

        WebRtcAgc_config_t config;
        config.targetLevelDbfs = targetLevelDbfsMode;
        config.compressionGaindB = compressionGaindBMode;
        config.limiterEnable = limiterEnableMode;

        return WebRtcAgc_set_config(agcInst,config);
}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    addFarend
 * Signature: (I[SI)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_addFarend
        (JNIEnv *env, jclass jclazz, jint agcInstance, jshortArray inFar, jint samples){
    return 0;
}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    addMic
 * Signature: (I[SII)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_addMic
        (JNIEnv *env, jclass jclazz, jint agcInstance, jshortArray inMic, jint num_bands, jint samples){
    return 0;
}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    getConfig
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_getConfig
        (JNIEnv *, jclass);

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    virtualMic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_virtualMic
        (JNIEnv *, jclass);

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    getAddFarendError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_getAddFarendError
        (JNIEnv *, jclass);

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_nsCreate
        (JNIEnv *env, jobject obj){
    NsHandle* handle = NULL;
    WebRtcNs_Create(&handle);

    return (int)handle;
}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_nsInit
        (JNIEnv *env, jobject obj, jint nsHandler, jint frequency){
    NsHandle *handler = (NsHandle *) nsHandler;
    if (handler == NULL){
        return -3;
    }
    return WebRtcNs_Init(handler,frequency);
}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    setPolicy
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_nsSetPolicy
        (JNIEnv *env, jobject obj, jint nsHandler, jint mode){

    NsHandle *handle = (NsHandle *) nsHandler;

    if (handle == NULL){
        return -3;
    }
    return WebRtcNs_set_policy(handle,mode);

}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    process
 * Signature: (I[SI[S)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_nsProcess
        (JNIEnv *env, jobject obj, jint nsHandler, jshortArray sample, jshortArray sample_H, jshortArray out,jshortArray out_H){
    NsHandle *handle = (NsHandle *) nsHandler;
    if(handle == NULL){
        return -3;
    }
    short* spframe = NULL;
    short* outframe = NULL;
    short* spframe_H = NULL;
    short* outframe_H = NULL;

    int ret = -1;
    spframe = (*env)->GetShortArrayElements(env,sample, NULL);
    outframe = (*env)->GetShortArrayElements(env,out, NULL);
    if(sample_H != NULL){
        spframe_H = (*env)->GetShortArrayElements(env,sample_H, NULL);
    }
    if(out_H != NULL){
        outframe_H = (*env)->GetShortArrayElements(env,out_H, NULL);
    }

    ret = WebRtcNs_Process(handle,spframe,spframe_H,outframe,outframe_H);

    (*env)->ReleaseShortArrayElements(env,sample, spframe, 0);
    (*env)->ReleaseShortArrayElements(env,out, outframe, 0);

    if(sample_H != NULL){
        (*env)->ReleaseShortArrayElements(env,sample_H, spframe_H, 0);
    }
    if(out_H != NULL){
        (*env)->ReleaseShortArrayElements(env,out_H, outframe_H, 0);
    }

    return ret;

}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    free
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_nsFree
         (JNIEnv *env, jobject obj, jint nsHandler){
    NsHandle *handle = (NsHandle *) nsHandler;
    if(handle == NULL){
        return -3;
    }

    return WebRtcNs_Free(handle);

}




                            /** NSX PROCESS*/



/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    nsxCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_nsxCreate
        (JNIEnv *env, jobject obj){

    NsHandle* handle = NULL;
    WebRtcNsx_Create(&handle);

    return (int)handle;

}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    nsxInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_nsxInit
        (JNIEnv *env, jobject obj, jint nsxHandler, jint frequency ){
    NsHandle *handler = (NsHandle *) nsxHandler;
    if (handler == NULL){
        return -3;
    }
    return WebRtcNsx_Init(handler,frequency);

}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    nsxSetPolicy
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_nsxSetPolicy
        (JNIEnv *env, jobject obj, jint nsxHandler, jint mode){
    NsHandle *handle = (NsHandle *) nsxHandler;

    if (handle == NULL){
        return -3;
    }
    return WebRtcNsx_set_policy(handle,mode);
}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    nsxProcess
 * Signature: (I[SI[S)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_nsxProcess
        (JNIEnv *env, jobject obj, jint nsxHandler, jshortArray sample, jshortArray sample_H, jshortArray out,jshortArray out_H){
    NsHandle *handle = (NsHandle *) nsxHandler;
    if(handle == NULL){
        return -3;
    }
    short* spframe = NULL;
    short* outframe = NULL;
    short* spframe_H = NULL;
    short* outframe_H = NULL;

    int ret = -1;
    spframe = (*env)->GetShortArrayElements(env,sample, NULL);
    outframe = (*env)->GetShortArrayElements(env,out, NULL);
    if(sample_H != NULL){
        spframe_H = (*env)->GetShortArrayElements(env,sample_H, NULL);
    }
    if(out_H != NULL){
        outframe_H = (*env)->GetShortArrayElements(env,out_H, NULL);
    }

    ret = WebRtcNsx_Process(handle,spframe,spframe_H,outframe,outframe_H);

    (*env)->ReleaseShortArrayElements(env,sample, spframe, 0);
    (*env)->ReleaseShortArrayElements(env,out, outframe, 0);

    if(sample_H != NULL){
        (*env)->ReleaseShortArrayElements(env,sample_H, spframe_H, 0);
    }
    if(out_H != NULL){
        (*env)->ReleaseShortArrayElements(env,out_H, outframe_H, 0);
    }

    return ret;
}

/*
 * Class:     com_wzc_tools_WebrtcUtils
 * Method:    nsxFree
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_com_wzc_tools_WebrtcUtils_nsxFree
        (JNIEnv *env, jobject obj, jint nsxHandler){
    NsHandle *handle = (NsHandle *) nsxHandler;
    if(handle == NULL){
        return -3;
    }

    return WebRtcNsx_Free(handle);
}

#ifdef __cplusplus
}
#endif
#endif
